### ISSUE TITLE
error code 002-0120

### ISSUE THREAD

**Issue by chris198685** [shinyquagsire23/MysteryMachine-Patcher#2]
Dear @shinyquagsire23 ,
Everything was ok in the emu sys version 10.7 before. 

I just maed a A9LH and updated EMU SYETEM to 11.0

A erroe code 002-0120 happened when I launched by HANS from BHL as usual.

I can't use MMP right now.

Pls tell me how to fix it.

Tks a lot.

![qq 20160525003800](https://cloud.githubusercontent.com/assets/12598742/15512266/92d711f0-2211-11e6-8885-1e300ed02bf0.jpg)
![qq 20160525003939](https://cloud.githubusercontent.com/assets/12598742/15512267/92e53cd0-2211-11e6-923e-c140b87969b2.jpg)

**Comment by shinyquagsire23** [comment]
Not an issue with my code, update your CFW.
